### Login
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "user5@teste.com",
  "password": "senhaUser5"
}


### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "user5@teste.com",
  "password": "senhaUser5"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami


### Sign out
POST http://localhost:3000/auth/signout

### Find a user
GET http://localhost:3000/auth/2
content-type: application/json

### Find a user by email
GET http://localhost:3000/auth?email=user1@teste.com
content-type: application/json

### Delete a user
DELETE http://localhost:3000/auth/3

### Update a user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "user2@teste.com",
  "password": "senhaUser2"
}